'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminTipoUbicacion
    Public Property nombre As String
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property id_sucursal As Nullable(Of Long)
    Public Property Activo As Nullable(Of Boolean)
    Public Property Clase As String
    Public Property Largo As Nullable(Of Integer)
    Public Property Ancho As Nullable(Of Integer)
    Public Property Alto As Nullable(Of Integer)
    Public Property Capacidad As Nullable(Of Integer)
    Public Property id_tipoCapacidad As Nullable(Of Long)

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property AdminTipoUbicacion1 As ICollection(Of AdminTipoUbicacion) = New HashSet(Of AdminTipoUbicacion)
    Public Overridable Property AdminTipoUbicacion2 As AdminTipoUbicacion
    Public Overridable Property Ubicaciones As ICollection(Of Ubicaciones) = New HashSet(Of Ubicaciones)

End Class
