'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminCamposAdicionales
    Public Property id As Long
    Public Property id_tipo As Long
    Public Property Campo As String
    Public Property Descripcion As String

    Public Overridable Property AdminTipoDocumento As AdminTipoDocumento
    Public Overridable Property Campos_Documentos As ICollection(Of Campos_Documentos) = New HashSet(Of Campos_Documentos)

End Class
