'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminSucursal
    Public Property Id As Long
    Public Property Sucursal As String
    Public Property id_cliente As Long
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Ciudad As String
    Public Property Departamento As String
    Public Property Activo As Boolean
    Public Property Prefijo As String
    Public Property id_ciudad As Nullable(Of Long)

    Public Overridable Property Admin_Ciudades As Admin_Ciudades
    Public Overridable Property AdminActividad As ICollection(Of AdminActividad) = New HashSet(Of AdminActividad)
    Public Overridable Property AdminClaseDocumento As ICollection(Of AdminClaseDocumento) = New HashSet(Of AdminClaseDocumento)
    Public Overridable Property AdminContacto As ICollection(Of AdminContacto) = New HashSet(Of AdminContacto)
    Public Overridable Property Clientes As Clientes
    Public Overridable Property AdminTablasReferencia As ICollection(Of AdminTablasReferencia) = New HashSet(Of AdminTablasReferencia)
    Public Overridable Property AdminTipoDocumento As ICollection(Of AdminTipoDocumento) = New HashSet(Of AdminTipoDocumento)
    Public Overridable Property AdminTipoTercero As ICollection(Of AdminTipoTercero) = New HashSet(Of AdminTipoTercero)
    Public Overridable Property AdminTipoUbicacion As ICollection(Of AdminTipoUbicacion) = New HashSet(Of AdminTipoUbicacion)
    Public Overridable Property Areas As ICollection(Of Areas) = New HashSet(Of Areas)
    Public Overridable Property Auditoria As ICollection(Of Auditoria) = New HashSet(Of Auditoria)
    Public Overridable Property Backups As ICollection(Of Backups) = New HashSet(Of Backups)
    Public Overridable Property Correspondencia As ICollection(Of Correspondencia) = New HashSet(Of Correspondencia)
    Public Overridable Property Documentos As ICollection(Of Documentos) = New HashSet(Of Documentos)
    Public Overridable Property Procesos As ICollection(Of Procesos) = New HashSet(Of Procesos)
    Public Overridable Property Solicitudes As ICollection(Of Solicitudes) = New HashSet(Of Solicitudes)
    Public Overridable Property Terceros As ICollection(Of Terceros) = New HashSet(Of Terceros)
    Public Overridable Property Ubicaciones As ICollection(Of Ubicaciones) = New HashSet(Of Ubicaciones)
    Public Overridable Property Usuario_Sucursal As ICollection(Of Usuario_Sucursal) = New HashSet(Of Usuario_Sucursal)

End Class
