'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Admin_AliasMenu
    Public Property id As Long
    Public Property id_cliente As Long
    Public Property id_menu As Long
    Public Property [Alias] As String

    Public Overridable Property Admin_Menu As Admin_Menu
    Public Overridable Property Clientes As Clientes

End Class
