'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminClaseDocumento
    Public Property id As Long
    Public Property ClaseDoc As String
    Public Property Descripcion As String
    Public Property id_sucursal As Nullable(Of Long)
    Public Property Activo As Boolean
    Public Property id_cliente As Nullable(Of Long)

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Clientes As Clientes
    Public Overridable Property AdminTipoDocumento As ICollection(Of AdminTipoDocumento) = New HashSet(Of AdminTipoDocumento)

End Class
