'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Admin_Ciudades
    Public Property codigo As Long
    Public Property ciudad As String
    Public Property departamento As String
    Public Property id_pais As Nullable(Of Long)

    Public Overridable Property AdminPais As AdminPais
    Public Overridable Property AdminContacto As ICollection(Of AdminContacto) = New HashSet(Of AdminContacto)
    Public Overridable Property AdminSucursal As ICollection(Of AdminSucursal) = New HashSet(Of AdminSucursal)
    Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
    Public Overridable Property SucursalTerceros As ICollection(Of SucursalTerceros) = New HashSet(Of SucursalTerceros)
    Public Overridable Property Terceros As ICollection(Of Terceros) = New HashSet(Of Terceros)

End Class
