'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminConsecutivo
    Public Property Id As Long
    Public Property id_cliente As Long
    Public Property Consecutivo As Nullable(Of Long)
    Public Property Anio As Nullable(Of Integer)
    Public Property Tipo As String

    Public Overridable Property Clientes As Clientes

End Class
