'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminContacto
    Public Property id As Long
    Public Property Nombre As String
    Public Property Telefono As String
    Public Property Cargo As String
    Public Property id_tercero As Nullable(Of Long)
    Public Property id_sucursal As Nullable(Of Long)
    Public Property Direccion As String
    Public Property Celular As String
    Public Property Correo As String
    Public Property id_ciudad As Nullable(Of Long)
    Public Property id_cliente As Nullable(Of Long)
    Public Property id_succliente As Nullable(Of Long)

    Public Overridable Property Admin_Ciudades As Admin_Ciudades
    Public Overridable Property AdminContacto1 As AdminContacto
    Public Overridable Property AdminContacto2 As AdminContacto
    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Clientes As Clientes
    Public Overridable Property SucursalTerceros As SucursalTerceros
    Public Overridable Property Terceros As Terceros

End Class
