'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminPais
    Public Property id As Long
    Public Property Pais As String

    Public Overridable Property Admin_Ciudades As ICollection(Of Admin_Ciudades) = New HashSet(Of Admin_Ciudades)

End Class
