'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Admin_Menu
    Public Property id As Long
    Public Property item As String
    Public Property link As String
    Public Property nivel As Integer
    Public Property id_menu As Nullable(Of Long)
    Public Property label As String

    Public Overridable Property Admin_AliasMenu As ICollection(Of Admin_AliasMenu) = New HashSet(Of Admin_AliasMenu)
    Public Overridable Property Admin_Menu1 As ICollection(Of Admin_Menu) = New HashSet(Of Admin_Menu)
    Public Overridable Property Admin_Menu2 As Admin_Menu
    Public Overridable Property Perfil_Menu As ICollection(Of Perfil_Menu) = New HashSet(Of Perfil_Menu)

End Class
