'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminPerfiles
    Public Property ID As Long
    Public Property nombre As String
    Public Property id_cliente As Nullable(Of Long)
    Public Property Activo As Nullable(Of Boolean)
    Public Property Descripcion As String

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Perfil_Menu As ICollection(Of Perfil_Menu) = New HashSet(Of Perfil_Menu)
    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)

End Class
