'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminTipoTercero
    Public Property Id As Long
    Public Property Tipo As String
    Public Property Descripcion As String
    Public Property Activo As Boolean
    Public Property id_sucursal As Nullable(Of Long)
    Public Property interno As Nullable(Of Boolean)
    Public Property proveedor As Nullable(Of Boolean)
    Public Property id_cliente As Nullable(Of Long)

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Listas_Tipo As ICollection(Of Listas_Tipo) = New HashSet(Of Listas_Tipo)
    Public Overridable Property Terceros As ICollection(Of Terceros) = New HashSet(Of Terceros)

End Class
