'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminTipoDocumento
    Public Property nombre As String
    Public Property descripcion As String
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property id_sucursal As Nullable(Of Long)
    Public Property Activo As Nullable(Of Boolean)
    Public Property id_clase As Nullable(Of Long)

    Public Overridable Property AdminCamposAdicionales As ICollection(Of AdminCamposAdicionales) = New HashSet(Of AdminCamposAdicionales)
    Public Overridable Property AdminClaseDocumento As AdminClaseDocumento
    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Clientes As Clientes
    Public Overridable Property Correspondencia As ICollection(Of Correspondencia) = New HashSet(Of Correspondencia)
    Public Overridable Property Documentos As ICollection(Of Documentos) = New HashSet(Of Documentos)
    Public Overridable Property Documentos_Requeridos As ICollection(Of Documentos_Requeridos) = New HashSet(Of Documentos_Requeridos)
    Public Overridable Property TipoDoc_TablaRetencion As ICollection(Of TipoDoc_TablaRetencion) = New HashSet(Of TipoDoc_TablaRetencion)
    Public Overridable Property ValidadorDocumentos As ICollection(Of ValidadorDocumentos) = New HashSet(Of ValidadorDocumentos)

End Class
