'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AdminTablasReferencia
    Public Property entidad As String
    Public Property oficina As String
    Public Property fecha As Date
    Public Property usuario As String
    Public Property responsable As String
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property id_sucursal As Nullable(Of Long)
    Public Property fechainicio As Nullable(Of Date)
    Public Property fechafin As Nullable(Of Date)
    Public Property Activo As Nullable(Of Boolean)
    Public Property Codigo As String
    Public Property id_area As Nullable(Of Long)

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Areas As Areas
    Public Overridable Property Clientes As Clientes
    Public Overridable Property TipoDoc_TablaRetencion As ICollection(Of TipoDoc_TablaRetencion) = New HashSet(Of TipoDoc_TablaRetencion)

End Class
