'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Areas
    Public Property nombre As String
    Public Property descripcion As String
    Public Property id_area As Nullable(Of Long)
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property id_sucursal As Nullable(Of Long)
    Public Property Activo As Nullable(Of Boolean)
    Public Property Color As String
    Public Property Codigo As String
    Public Property Prefijo As String

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property AdminTablasReferencia As ICollection(Of AdminTablasReferencia) = New HashSet(Of AdminTablasReferencia)
    Public Overridable Property Areas1 As ICollection(Of Areas) = New HashSet(Of Areas)
    Public Overridable Property Areas2 As Areas
    Public Overridable Property Clientes As Clientes
    Public Overridable Property Documentos_Area As ICollection(Of Documentos_Area) = New HashSet(Of Documentos_Area)
    Public Overridable Property Terceros As ICollection(Of Terceros) = New HashSet(Of Terceros)
    Public Overridable Property Usuarios_Areas As ICollection(Of Usuarios_Areas) = New HashSet(Of Usuarios_Areas)

End Class
