'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Backups
    Public Property id As Long
    Public Property id_usuario As Long
    Public Property Fecha_solicitud As Date
    Public Property fecha_respuesta As Date
    Public Property Estado As String
    Public Property Ruta As String
    Public Property id_cliente As Long
    Public Property id_sucursal As Nullable(Of Long)

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Clientes As Clientes

End Class
