'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Campos_Documentos
    Public Property id As Long
    Public Property id_doc As Long
    Public Property id_campo As Long
    Public Property valor As String

    Public Overridable Property AdminCamposAdicionales As AdminCamposAdicionales
    Public Overridable Property Documentos As Documentos

End Class
