'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property nombre As String
    Public Property tipo_documento As String
    Public Property numero_documento As Long
    Public Property direccion As String
    Public Property telefono As String
    Public Property celular As String
    Public Property correo_electronico As String
    Public Property fecha_creacion As Date
    Public Property id As Long
    Public Property Logo As String
    Public Property Inicio As String
    Public Property id_ciudad As Nullable(Of Long)
    Public Property Prefijo As String

    Public Overridable Property Admin_AliasMenu As ICollection(Of Admin_AliasMenu) = New HashSet(Of Admin_AliasMenu)
    Public Overridable Property Admin_Ciudades As Admin_Ciudades
    Public Overridable Property AdminActividad As ICollection(Of AdminActividad) = New HashSet(Of AdminActividad)
    Public Overridable Property AdminClaseDocumento As ICollection(Of AdminClaseDocumento) = New HashSet(Of AdminClaseDocumento)
    Public Overridable Property AdminConsecutivo As ICollection(Of AdminConsecutivo) = New HashSet(Of AdminConsecutivo)
    Public Overridable Property AdminContacto As ICollection(Of AdminContacto) = New HashSet(Of AdminContacto)
    Public Overridable Property AdminPerfiles As ICollection(Of AdminPerfiles) = New HashSet(Of AdminPerfiles)
    Public Overridable Property AdminSucursal As ICollection(Of AdminSucursal) = New HashSet(Of AdminSucursal)
    Public Overridable Property AdminTablasReferencia As ICollection(Of AdminTablasReferencia) = New HashSet(Of AdminTablasReferencia)
    Public Overridable Property AdminTipoDocumento As ICollection(Of AdminTipoDocumento) = New HashSet(Of AdminTipoDocumento)
    Public Overridable Property Areas As ICollection(Of Areas) = New HashSet(Of Areas)
    Public Overridable Property Backups As ICollection(Of Backups) = New HashSet(Of Backups)
    Public Overridable Property Contratos_Cliente As ICollection(Of Contratos_Cliente) = New HashSet(Of Contratos_Cliente)
    Public Overridable Property Documentos As ICollection(Of Documentos) = New HashSet(Of Documentos)
    Public Overridable Property Terceros As ICollection(Of Terceros) = New HashSet(Of Terceros)
    Public Overridable Property Usuario_Cliente As ICollection(Of Usuario_Cliente) = New HashSet(Of Usuario_Cliente)

End Class
