'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comentarios_Correspondencia
    Public Property id As Long
    Public Property id_correspondencia As Long
    Public Property Fecha As Date
    Public Property Comentario As String
    Public Property id_tercero As Long

    Public Overridable Property Correspondencia As Correspondencia
    Public Overridable Property Terceros As Terceros

End Class
