'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contratos_Cliente
    Public Property id As Long
    Public Property id_cliente As Long
    Public Property Nro_Contrato As String
    Public Property Fecha_inicio As Date
    Public Property Fecha_fin As Date
    Public Property Tipo_Pago As String
    Public Property Estado As String
    Public Property Licencia As String

    Public Overridable Property Clientes As Clientes

End Class
