'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Correspondencia
    Public Property numero_radicado As String
    Public Property fecha_documento As Date
    Public Property fecha_sistema As Date
    Public Property ciudad_remitente As String
    Public Property tipo_ingreso As String
    Public Property tipo_correspondencia As String
    Public Property remitente As String
    Public Property dependencia_remitente As String
    Public Property asunto As String
    Public Property sticker As String
    Public Property id_sucursal As Long
    Public Property id As Long
    Public Property tipo_envio As String
    Public Property guia As String
    Public Property usuario As String
    Public Property observaciones As String
    Public Property id_mensajeria As Nullable(Of Long)
    Public Property id_responsable As Nullable(Of Long)
    Public Property Estado As String
    Public Property id_tipodoc As Nullable(Of Long)
    Public Property folios As Nullable(Of Long)
    Public Property paquetes As Nullable(Of Integer)
    Public Property Fecha_respuesta As Nullable(Of Date)
    Public Property Respuesta As String
    Public Property id_original As Nullable(Of Long)

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property AdminTipoDocumento As AdminTipoDocumento
    Public Overridable Property Comentarios_Correspondencia As ICollection(Of Comentarios_Correspondencia) = New HashSet(Of Comentarios_Correspondencia)
    Public Overridable Property Correspondencia1 As ICollection(Of Correspondencia) = New HashSet(Of Correspondencia)
    Public Overridable Property Correspondencia2 As Correspondencia
    Public Overridable Property Terceros As Terceros
    Public Overridable Property Terceros1 As Terceros
    Public Overridable Property Documentos_Correspondencia As ICollection(Of Documentos_Correspondencia) = New HashSet(Of Documentos_Correspondencia)
    Public Overridable Property Terceros_Correspondencia As ICollection(Of Terceros_Correspondencia) = New HashSet(Of Terceros_Correspondencia)

End Class
