'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Core.Objects
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class DAPP_BDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DAPP_BDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Admin_AliasMenu() As DbSet(Of Admin_AliasMenu)
    Public Property Admin_Ciudades() As DbSet(Of Admin_Ciudades)
    Public Property Admin_Menu() As DbSet(Of Admin_Menu)
    Public Property Admin_Perfiles() As DbSet(Of Admin_Perfiles)
    Public Property AdminActividad() As DbSet(Of AdminActividad)
    Public Property AdminCamposAdicionales() As DbSet(Of AdminCamposAdicionales)
    Public Property AdminClaseDocumento() As DbSet(Of AdminClaseDocumento)
    Public Property AdminConsecutivo() As DbSet(Of AdminConsecutivo)
    Public Property AdminContacto() As DbSet(Of AdminContacto)
    Public Property AdminPais() As DbSet(Of AdminPais)
    Public Property AdminPerfiles() As DbSet(Of AdminPerfiles)
    Public Property AdminSucursal() As DbSet(Of AdminSucursal)
    Public Property AdminTablasReferencia() As DbSet(Of AdminTablasReferencia)
    Public Property AdminTipoDocumento() As DbSet(Of AdminTipoDocumento)
    Public Property AdminTipoTercero() As DbSet(Of AdminTipoTercero)
    Public Property AdminTipoUbicacion() As DbSet(Of AdminTipoUbicacion)
    Public Property Areas() As DbSet(Of Areas)
    Public Property Auditoria() As DbSet(Of Auditoria)
    Public Property Backups() As DbSet(Of Backups)
    Public Property Campos_Documentos() As DbSet(Of Campos_Documentos)
    Public Property Clientes() As DbSet(Of Clientes)
    Public Property Comentarios_Correspondencia() As DbSet(Of Comentarios_Correspondencia)
    Public Property Contratos_Cliente() As DbSet(Of Contratos_Cliente)
    Public Property Correspondencia() As DbSet(Of Correspondencia)
    Public Property Documentos() As DbSet(Of Documentos)
    Public Property Documentos_Area() As DbSet(Of Documentos_Area)
    Public Property Documentos_Correspondencia() As DbSet(Of Documentos_Correspondencia)
    Public Property Documentos_Requeridos() As DbSet(Of Documentos_Requeridos)
    Public Property Documentos_Solicitud() As DbSet(Of Documentos_Solicitud)
    Public Property Documentos_Terceros() As DbSet(Of Documentos_Terceros)
    Public Property DocumentosArchigex() As DbSet(Of DocumentosArchigex)
    Public Property Listas_Tipo() As DbSet(Of Listas_Tipo)
    Public Property Perfil_Menu() As DbSet(Of Perfil_Menu)
    Public Property Procesos() As DbSet(Of Procesos)
    Public Property Solicitudes() As DbSet(Of Solicitudes)
    Public Property SucursalTerceros() As DbSet(Of SucursalTerceros)
    Public Property Terceros() As DbSet(Of Terceros)
    Public Property Terceros_Correspondencia() As DbSet(Of Terceros_Correspondencia)
    Public Property TipoDoc_TablaRetencion() As DbSet(Of TipoDoc_TablaRetencion)
    Public Property Transferencias() As DbSet(Of Transferencias)
    Public Property Ubicaciones() As DbSet(Of Ubicaciones)
    Public Property Usuario_Cliente() As DbSet(Of Usuario_Cliente)
    Public Property Usuario_Sucursal() As DbSet(Of Usuario_Sucursal)
    Public Property Usuarios_Areas() As DbSet(Of Usuarios_Areas)
    Public Property Usuarios_Terceros() As DbSet(Of Usuarios_Terceros)
    Public Property ValidadorDocumentos() As DbSet(Of ValidadorDocumentos)
    Public Property Version_Documento() As DbSet(Of Version_Documento)
    Public Property TERCEROS_temp() As DbSet(Of TERCEROS_temp)
    Public Property Usuarios() As DbSet(Of Usuarios)

    Public Overridable Function BuscarCliente(filtro As String) As ObjectResult(Of BuscarCliente_Result)
        Dim filtroParameter As ObjectParameter = If(filtro IsNot Nothing, New ObjectParameter("Filtro", filtro), New ObjectParameter("Filtro", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of BuscarCliente_Result)("BuscarCliente", filtroParameter)
    End Function

    Public Overridable Function BuscarTercero(filtro As String, sucursal As Nullable(Of Long), interno As Nullable(Of Integer), correspondencia As Nullable(Of Integer)) As ObjectResult(Of BuscarTercero_Result)
        Dim filtroParameter As ObjectParameter = If(filtro IsNot Nothing, New ObjectParameter("Filtro", filtro), New ObjectParameter("Filtro", GetType(String)))

        Dim sucursalParameter As ObjectParameter = If(sucursal.HasValue, New ObjectParameter("Sucursal", sucursal), New ObjectParameter("Sucursal", GetType(Long)))

        Dim internoParameter As ObjectParameter = If(interno.HasValue, New ObjectParameter("interno", interno), New ObjectParameter("interno", GetType(Integer)))

        Dim correspondenciaParameter As ObjectParameter = If(correspondencia.HasValue, New ObjectParameter("correspondencia", correspondencia), New ObjectParameter("correspondencia", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of BuscarTercero_Result)("BuscarTercero", filtroParameter, sucursalParameter, internoParameter, correspondenciaParameter)
    End Function

    Public Overridable Function PasswordChange(usuario As String, old_password As String, new_password As String) As Integer
        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Dim old_passwordParameter As ObjectParameter = If(old_password IsNot Nothing, New ObjectParameter("old_password", old_password), New ObjectParameter("old_password", GetType(String)))

        Dim new_passwordParameter As ObjectParameter = If(new_password IsNot Nothing, New ObjectParameter("new_password", new_password), New ObjectParameter("new_password", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PasswordChange", usuarioParameter, old_passwordParameter, new_passwordParameter)
    End Function

    Public Overridable Function PasswordGet(usuario As String) As ObjectResult(Of PasswordGet_Result)
        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PasswordGet_Result)("PasswordGet", usuarioParameter)
    End Function

    Public Overridable Function Buscar_lista(lista As String, sucursal As String) As ObjectResult(Of Buscar_lista_Result)
        Dim listaParameter As ObjectParameter = If(lista IsNot Nothing, New ObjectParameter("lista", lista), New ObjectParameter("lista", GetType(String)))

        Dim sucursalParameter As ObjectParameter = If(sucursal IsNot Nothing, New ObjectParameter("sucursal", sucursal), New ObjectParameter("sucursal", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Buscar_lista_Result)("Buscar_lista", listaParameter, sucursalParameter)
    End Function

    Public Overridable Function Alerta_Archivo(sucursal As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Integer))
        Dim sucursalParameter As ObjectParameter = If(sucursal.HasValue, New ObjectParameter("sucursal", sucursal), New ObjectParameter("sucursal", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("Alerta_Archivo", sucursalParameter)
    End Function

    Public Overridable Function Alerta_correspondencia(usuario As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Integer))
        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("Alerta_correspondencia", usuarioParameter)
    End Function

    Public Overridable Function Alerta_Listas(cliente As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Integer))
        Dim clienteParameter As ObjectParameter = If(cliente.HasValue, New ObjectParameter("cliente", cliente), New ObjectParameter("cliente", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("Alerta_Listas", clienteParameter)
    End Function

    Public Overridable Function Alerta_prestamo(cliente As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Integer))
        Dim clienteParameter As ObjectParameter = If(cliente.HasValue, New ObjectParameter("cliente", cliente), New ObjectParameter("cliente", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("Alerta_prestamo", clienteParameter)
    End Function

    Public Overridable Function ClaseDoc_ubicacion(ubicacion As Nullable(Of Long)) As ObjectResult(Of String)
        Dim ubicacionParameter As ObjectParameter = If(ubicacion.HasValue, New ObjectParameter("ubicacion", ubicacion), New ObjectParameter("ubicacion", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("ClaseDoc_ubicacion", ubicacionParameter)
    End Function

    Public Overridable Function Folios_ubicacion(ubicacion As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Long))
        Dim ubicacionParameter As ObjectParameter = If(ubicacion.HasValue, New ObjectParameter("ubicacion", ubicacion), New ObjectParameter("ubicacion", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Long))("Folios_ubicacion", ubicacionParameter)
    End Function

    Public Overridable Function TiposDoc_ubicacion(ubicacion As Nullable(Of Long)) As ObjectResult(Of String)
        Dim ubicacionParameter As ObjectParameter = If(ubicacion.HasValue, New ObjectParameter("ubicacion", ubicacion), New ObjectParameter("ubicacion", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("TiposDoc_ubicacion", ubicacionParameter)
    End Function

    Public Overridable Function GetStickerCorrespondencia(id_correspondencia As Nullable(Of Long)) As ObjectResult(Of GetStickerCorrespondencia_Result)
        Dim id_correspondenciaParameter As ObjectParameter = If(id_correspondencia.HasValue, New ObjectParameter("id_correspondencia", id_correspondencia), New ObjectParameter("id_correspondencia", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetStickerCorrespondencia_Result)("GetStickerCorrespondencia", id_correspondenciaParameter)
    End Function

    Public Overridable Function ActualizarDocumentos(url As String, nuevoTipo As String) As Integer
        Dim urlParameter As ObjectParameter = If(url IsNot Nothing, New ObjectParameter("url", url), New ObjectParameter("url", GetType(String)))

        Dim nuevoTipoParameter As ObjectParameter = If(nuevoTipo IsNot Nothing, New ObjectParameter("nuevoTipo", nuevoTipo), New ObjectParameter("nuevoTipo", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizarDocumentos", urlParameter, nuevoTipoParameter)
    End Function

    Public Overridable Function ActualizarMetricasListaChequeoSeguros() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizarMetricasListaChequeoSeguros")
    End Function

    Public Overridable Function ActualizarMetricasSegurosRamos() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizarMetricasSegurosRamos")
    End Function

    Public Overridable Function ActualizarMetricasWorkflow() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizarMetricasWorkflow")
    End Function

    Public Overridable Function ActualizarMetricasWorkflowAnexos() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizarMetricasWorkflowAnexos")
    End Function

    Public Overridable Function ActualizarNegociosLeasing() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizarNegociosLeasing")
    End Function

    Public Overridable Function AdicionarCuentaCliente(id_empresa As Nullable(Of Long)) As Integer
        Dim id_empresaParameter As ObjectParameter = If(id_empresa.HasValue, New ObjectParameter("id_empresa", id_empresa), New ObjectParameter("id_empresa", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AdicionarCuentaCliente", id_empresaParameter)
    End Function

    Public Overridable Function AgregarURL(nombre As String, url As String, id_estado As Nullable(Of Long), mSysId As Nullable(Of Long)) As Integer
        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim urlParameter As ObjectParameter = If(url IsNot Nothing, New ObjectParameter("Url", url), New ObjectParameter("Url", GetType(String)))

        Dim id_estadoParameter As ObjectParameter = If(id_estado.HasValue, New ObjectParameter("id_estado", id_estado), New ObjectParameter("id_estado", GetType(Long)))

        Dim mSysIdParameter As ObjectParameter = If(mSysId.HasValue, New ObjectParameter("MSysId", mSysId), New ObjectParameter("MSysId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AgregarURL", nombreParameter, urlParameter, id_estadoParameter, mSysIdParameter)
    End Function

    Public Overridable Function canRemoveRamo(codigoRamo_ As Nullable(Of Integer)) As Integer
        Dim codigoRamo_Parameter As ObjectParameter = If(codigoRamo_.HasValue, New ObjectParameter("CodigoRamo_", codigoRamo_), New ObjectParameter("CodigoRamo_", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("canRemoveRamo", codigoRamo_Parameter)
    End Function

    Public Overridable Function Cubo_PolizasSileasing() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Cubo_PolizasSileasing")
    End Function

    Public Overridable Function Cubo_PolizasSistema() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Cubo_PolizasSistema")
    End Function

    Public Overridable Function CuboMetricasSegurosRamos() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CuboMetricasSegurosRamos")
    End Function

    Public Overridable Function EliminarDocumentos(url As String) As Integer
        Dim urlParameter As ObjectParameter = If(url IsNot Nothing, New ObjectParameter("url", url), New ObjectParameter("url", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("EliminarDocumentos", urlParameter)
    End Function

    Public Overridable Function EliminarURL(mSysId As Nullable(Of Long)) As Integer
        Dim mSysIdParameter As ObjectParameter = If(mSysId.HasValue, New ObjectParameter("MSysId", mSysId), New ObjectParameter("MSysId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("EliminarURL", mSysIdParameter)
    End Function

    Public Overridable Function ExportarEstados(idProceso As Nullable(Of Long), servidor As String, nombreDB As String, idProcesoNuevo As Nullable(Of Long)) As Integer
        Dim idProcesoParameter As ObjectParameter = If(idProceso.HasValue, New ObjectParameter("idProceso", idProceso), New ObjectParameter("idProceso", GetType(Long)))

        Dim servidorParameter As ObjectParameter = If(servidor IsNot Nothing, New ObjectParameter("Servidor", servidor), New ObjectParameter("Servidor", GetType(String)))

        Dim nombreDBParameter As ObjectParameter = If(nombreDB IsNot Nothing, New ObjectParameter("NombreDB", nombreDB), New ObjectParameter("NombreDB", GetType(String)))

        Dim idProcesoNuevoParameter As ObjectParameter = If(idProcesoNuevo.HasValue, New ObjectParameter("IdProcesoNuevo", idProcesoNuevo), New ObjectParameter("IdProcesoNuevo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ExportarEstados", idProcesoParameter, servidorParameter, nombreDBParameter, idProcesoNuevoParameter)
    End Function

    Public Overridable Function ExportarProceso(idProceso As Nullable(Of Long), servidor As String, nombreDB As String) As Integer
        Dim idProcesoParameter As ObjectParameter = If(idProceso.HasValue, New ObjectParameter("idProceso", idProceso), New ObjectParameter("idProceso", GetType(Long)))

        Dim servidorParameter As ObjectParameter = If(servidor IsNot Nothing, New ObjectParameter("Servidor", servidor), New ObjectParameter("Servidor", GetType(String)))

        Dim nombreDBParameter As ObjectParameter = If(nombreDB IsNot Nothing, New ObjectParameter("NombreDB", nombreDB), New ObjectParameter("NombreDB", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ExportarProceso", idProcesoParameter, servidorParameter, nombreDBParameter)
    End Function

    Public Overridable Function getDatosCargaArchivo(idSegmento As Nullable(Of Integer), id_empresa As Nullable(Of Long)) As Integer
        Dim idSegmentoParameter As ObjectParameter = If(idSegmento.HasValue, New ObjectParameter("idSegmento", idSegmento), New ObjectParameter("idSegmento", GetType(Integer)))

        Dim id_empresaParameter As ObjectParameter = If(id_empresa.HasValue, New ObjectParameter("id_empresa", id_empresa), New ObjectParameter("id_empresa", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getDatosCargaArchivo", idSegmentoParameter, id_empresaParameter)
    End Function

    Public Overridable Function getDocsByIdRelacionado(id As Nullable(Of Long)) As ObjectResult(Of getDocsByIdRelacionado_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of getDocsByIdRelacionado_Result)("getDocsByIdRelacionado", idParameter)
    End Function

    Public Overridable Function getDocsCliente(nit_cliente_ As Nullable(Of Long)) As Integer
        Dim nit_cliente_Parameter As ObjectParameter = If(nit_cliente_.HasValue, New ObjectParameter("Nit_cliente_", nit_cliente_), New ObjectParameter("Nit_cliente_", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getDocsCliente", nit_cliente_Parameter)
    End Function

    Public Overridable Function getEstadosProceso(proceso As Nullable(Of Long)) As Integer
        Dim procesoParameter As ObjectParameter = If(proceso.HasValue, New ObjectParameter("proceso", proceso), New ObjectParameter("proceso", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getEstadosProceso", procesoParameter)
    End Function

    Public Overridable Function getFestivos() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getFestivos")
    End Function

    Public Overridable Function getMacroProcesosBySegmento(idSegmento As Nullable(Of Integer)) As Integer
        Dim idSegmentoParameter As ObjectParameter = If(idSegmento.HasValue, New ObjectParameter("idSegmento", idSegmento), New ObjectParameter("idSegmento", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getMacroProcesosBySegmento", idSegmentoParameter)
    End Function

    Public Overridable Function getRamosByNitOrAll(nit As Nullable(Of Double), all As Nullable(Of Boolean)) As Integer
        Dim nitParameter As ObjectParameter = If(nit.HasValue, New ObjectParameter("nit", nit), New ObjectParameter("nit", GetType(Double)))

        Dim allParameter As ObjectParameter = If(all.HasValue, New ObjectParameter("all", all), New ObjectParameter("all", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getRamosByNitOrAll", nitParameter, allParameter)
    End Function

    Public Overridable Function getURLByEstado(id_estado As Nullable(Of Long)) As Integer
        Dim id_estadoParameter As ObjectParameter = If(id_estado.HasValue, New ObjectParameter("id_estado", id_estado), New ObjectParameter("id_estado", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("getURLByEstado", id_estadoParameter)
    End Function

    Public Overridable Function QryDocumentos(cubo As String, usuario As String, fecha_inicial As Nullable(Of Date), fecha_final As Nullable(Of Date), criterio As String, page_index As Nullable(Of Integer), page_size As Nullable(Of Integer)) As Integer
        Dim cuboParameter As ObjectParameter = If(cubo IsNot Nothing, New ObjectParameter("cubo", cubo), New ObjectParameter("cubo", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Dim fecha_inicialParameter As ObjectParameter = If(fecha_inicial.HasValue, New ObjectParameter("fecha_inicial", fecha_inicial), New ObjectParameter("fecha_inicial", GetType(Date)))

        Dim fecha_finalParameter As ObjectParameter = If(fecha_final.HasValue, New ObjectParameter("fecha_final", fecha_final), New ObjectParameter("fecha_final", GetType(Date)))

        Dim criterioParameter As ObjectParameter = If(criterio IsNot Nothing, New ObjectParameter("criterio", criterio), New ObjectParameter("criterio", GetType(String)))

        Dim page_indexParameter As ObjectParameter = If(page_index.HasValue, New ObjectParameter("page_index", page_index), New ObjectParameter("page_index", GetType(Integer)))

        Dim page_sizeParameter As ObjectParameter = If(page_size.HasValue, New ObjectParameter("page_size", page_size), New ObjectParameter("page_size", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("QryDocumentos", cuboParameter, usuarioParameter, fecha_inicialParameter, fecha_finalParameter, criterioParameter, page_indexParameter, page_sizeParameter)
    End Function

    Public Overridable Function UpdateRamo(iD As Nullable(Of Long), codigoRamo_ As Nullable(Of Integer), nombreRamo_ As String, grupoRamo_ As Nullable(Of Integer), uEN_Codigo_ As String, iva_ramo_ As Nullable(Of Double), comision_ramo_ As Nullable(Of Double), iva_comision_ As Nullable(Of Double), min_comision_ As Nullable(Of Double), max_comision_ As Nullable(Of Double), tasa_prima_ As Nullable(Of Double), tasa_comision_ As Nullable(Of Double), tasa_comision_minima_ As Nullable(Of Double), tasa_comision_maxima_ As Nullable(Of Double)) As Integer
        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Long)))

        Dim codigoRamo_Parameter As ObjectParameter = If(codigoRamo_.HasValue, New ObjectParameter("CodigoRamo_", codigoRamo_), New ObjectParameter("CodigoRamo_", GetType(Integer)))

        Dim nombreRamo_Parameter As ObjectParameter = If(nombreRamo_ IsNot Nothing, New ObjectParameter("NombreRamo_", nombreRamo_), New ObjectParameter("NombreRamo_", GetType(String)))

        Dim grupoRamo_Parameter As ObjectParameter = If(grupoRamo_.HasValue, New ObjectParameter("GrupoRamo_", grupoRamo_), New ObjectParameter("GrupoRamo_", GetType(Integer)))

        Dim uEN_Codigo_Parameter As ObjectParameter = If(uEN_Codigo_ IsNot Nothing, New ObjectParameter("UEN_Codigo_", uEN_Codigo_), New ObjectParameter("UEN_Codigo_", GetType(String)))

        Dim iva_ramo_Parameter As ObjectParameter = If(iva_ramo_.HasValue, New ObjectParameter("iva_ramo_", iva_ramo_), New ObjectParameter("iva_ramo_", GetType(Double)))

        Dim comision_ramo_Parameter As ObjectParameter = If(comision_ramo_.HasValue, New ObjectParameter("comision_ramo_", comision_ramo_), New ObjectParameter("comision_ramo_", GetType(Double)))

        Dim iva_comision_Parameter As ObjectParameter = If(iva_comision_.HasValue, New ObjectParameter("iva_comision_", iva_comision_), New ObjectParameter("iva_comision_", GetType(Double)))

        Dim min_comision_Parameter As ObjectParameter = If(min_comision_.HasValue, New ObjectParameter("min_comision_", min_comision_), New ObjectParameter("min_comision_", GetType(Double)))

        Dim max_comision_Parameter As ObjectParameter = If(max_comision_.HasValue, New ObjectParameter("max_comision_", max_comision_), New ObjectParameter("max_comision_", GetType(Double)))

        Dim tasa_prima_Parameter As ObjectParameter = If(tasa_prima_.HasValue, New ObjectParameter("tasa_prima_", tasa_prima_), New ObjectParameter("tasa_prima_", GetType(Double)))

        Dim tasa_comision_Parameter As ObjectParameter = If(tasa_comision_.HasValue, New ObjectParameter("tasa_comision_", tasa_comision_), New ObjectParameter("tasa_comision_", GetType(Double)))

        Dim tasa_comision_minima_Parameter As ObjectParameter = If(tasa_comision_minima_.HasValue, New ObjectParameter("tasa_comision_minima_", tasa_comision_minima_), New ObjectParameter("tasa_comision_minima_", GetType(Double)))

        Dim tasa_comision_maxima_Parameter As ObjectParameter = If(tasa_comision_maxima_.HasValue, New ObjectParameter("tasa_comision_maxima_", tasa_comision_maxima_), New ObjectParameter("tasa_comision_maxima_", GetType(Double)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UpdateRamo", iDParameter, codigoRamo_Parameter, nombreRamo_Parameter, grupoRamo_Parameter, uEN_Codigo_Parameter, iva_ramo_Parameter, comision_ramo_Parameter, iva_comision_Parameter, min_comision_Parameter, max_comision_Parameter, tasa_prima_Parameter, tasa_comision_Parameter, tasa_comision_minima_Parameter, tasa_comision_maxima_Parameter)
    End Function

    Public Overridable Function UpdateReporte(tabla As String) As Integer
        Dim tablaParameter As ObjectParameter = If(tabla IsNot Nothing, New ObjectParameter("Tabla", tabla), New ObjectParameter("Tabla", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UpdateReporte", tablaParameter)
    End Function

    Public Overridable Function UpdateUsuariosEquipo() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UpdateUsuariosEquipo")
    End Function

End Class
