'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Documentos
    Public Property nombre As String
    Public Property descripcion As String
    Public Property archivo As Byte()
    Public Property version As Integer
    Public Property fecha_creacion As Date
    Public Property fecha_modificacion As Nullable(Of Date)
    Public Property usuario As String
    Public Property id_tipo As Long
    Public Property id_ubicacion As Nullable(Of Long)
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property id_sucursal As Nullable(Of Long)
    Public Property [alias] As String
    Public Property folios As Nullable(Of Long)
    Public Property extension As String
    Public Property fechadoc As Nullable(Of Date)
    Public Property FGestion As Nullable(Of Date)
    Public Property FCentral As Nullable(Of Date)
    Public Property FHistorico As Nullable(Of Date)
    Public Property Estado As String

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property AdminTipoDocumento As AdminTipoDocumento
    Public Overridable Property Campos_Documentos As ICollection(Of Campos_Documentos) = New HashSet(Of Campos_Documentos)
    Public Overridable Property Clientes As Clientes
    Public Overridable Property Documentos_Area As ICollection(Of Documentos_Area) = New HashSet(Of Documentos_Area)
    Public Overridable Property Documentos_Correspondencia As ICollection(Of Documentos_Correspondencia) = New HashSet(Of Documentos_Correspondencia)
    Public Overridable Property Documentos_Solicitud As ICollection(Of Documentos_Solicitud) = New HashSet(Of Documentos_Solicitud)
    Public Overridable Property Documentos_Terceros As ICollection(Of Documentos_Terceros) = New HashSet(Of Documentos_Terceros)
    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property DocumentosArchigex As ICollection(Of DocumentosArchigex) = New HashSet(Of DocumentosArchigex)
    Public Overridable Property Transferencias As ICollection(Of Transferencias) = New HashSet(Of Transferencias)
    Public Overridable Property Version_Documento As ICollection(Of Version_Documento) = New HashSet(Of Version_Documento)

End Class
