'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Documentos_Terceros
    Public Property id_tercero As Long
    Public Property id_documento As Long
    Public Property id As Long

    Public Overridable Property Documentos As Documentos
    Public Overridable Property Terceros As Terceros

End Class
