'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Perfil_Menu
    Public Property id As Long
    Public Property id_menu As Long
    Public Property id_perfil As Long
    Public Property Adicion As Boolean
    Public Property Edicion As Boolean
    Public Property Consulta As Boolean

    Public Overridable Property Admin_Menu As Admin_Menu
    Public Overridable Property AdminPerfiles As AdminPerfiles

End Class
