'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Procesos
    Public Property proceso As String
    Public Property descripcion As String
    Public Property id_sucursal As Long
    Public Property id As Long
    Public Property Activo As Boolean

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Documentos_Requeridos As ICollection(Of Documentos_Requeridos) = New HashSet(Of Documentos_Requeridos)
    Public Overridable Property Listas_Tipo As ICollection(Of Listas_Tipo) = New HashSet(Of Listas_Tipo)

End Class
