'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Segmentos
    Public Property empresa_id As Long
    Public Property nombre As String
    Public Property MSysID As Integer

    Public Overridable Property UsuariosSegmento As ICollection(Of UsuariosSegmento) = New HashSet(Of UsuariosSegmento)

End Class
