'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Solicitudes
    Public Property id As Long
    Public Property Fecha As Date
    Public Property Fecha_prestamo As Nullable(Of Date)
    Public Property Fecha_estimada As Nullable(Of Date)
    Public Property fecha_devolucion As Nullable(Of Date)
    Public Property id_ubicacion As Nullable(Of Long)
    Public Property id_solicitante As Long
    Public Property id_responsable As Nullable(Of Long)
    Public Property duracion As Integer
    Public Property Estado As String
    Public Property id_sucursal As Long
    Public Property motivo As String
    Public Property observaciones As String

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property Documentos_Solicitud As ICollection(Of Documentos_Solicitud) = New HashSet(Of Documentos_Solicitud)
    Public Overridable Property Terceros As Terceros
    Public Overridable Property Terceros1 As Terceros
    Public Overridable Property Ubicaciones As Ubicaciones

End Class
