'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SucursalTerceros
    Public Property nombre As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property correo_electronico As String
    Public Property id As Long
    Public Property id_tercero As Long
    Public Property Activo As Boolean
    Public Property id_ciudad As Nullable(Of Long)

    Public Overridable Property Admin_Ciudades As Admin_Ciudades
    Public Overridable Property AdminContacto As ICollection(Of AdminContacto) = New HashSet(Of AdminContacto)
    Public Overridable Property SucursalTerceros1 As SucursalTerceros
    Public Overridable Property SucursalTerceros2 As SucursalTerceros
    Public Overridable Property Terceros As Terceros

End Class
