'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TERCEROS_temp
    Public Property NIT As String
    Public Property DIGITO_DE_CHEQUEO As String
    Public Property nit_con_digito_chequeo As String
    Public Property NOMBRE_DE_LA_EMPRESA As String
    Public Property terdir As String
    Public Property email As String
    Public Property terfax As String
    Public Property EXTERIOR As Boolean
    Public Property terid As Nullable(Of Double)
    Public Property NOMBRE_1 As String
    Public Property NOMBRE_2 As String
    Public Property APELLIDO_1 As String
    Public Property APELLIDO_2 As String
    Public Property ciucod As String
    Public Property paicod As String
    Public Property CELULAR As String
    Public Property PROVEEDOR As Boolean
    Public Property CLIENTE As Boolean
    Public Property EMPLEADO As Boolean
    Public Property terperso As Nullable(Of Double)
    Public Property REGIMEN As String
    Public Property RZN_SOCIAL As String
    Public Property TELEFONO As String
    Public Property TIPO_DE_DOCUMENTO As String
    Public Property terweb As String
    Public Property ESTADO As Nullable(Of Double)

End Class
