'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Terceros
    Public Property nombre As String
    Public Property tipo_documento As String
    Public Property numero_documento As Long
    Public Property direccion As String
    Public Property telefono As String
    Public Property celular As String
    Public Property correo_electronico As String
    Public Property fecha_creacion As Date
    Public Property usuario As String
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property id_sucursal As Nullable(Of Long)
    Public Property Activo As Nullable(Of Boolean)
    Public Property id_tipo As Nullable(Of Long)
    Public Property id_actividad As Nullable(Of Long)
    Public Property sector As String
    Public Property id_area As Nullable(Of Long)
    Public Property id_jefe As Nullable(Of Long)
    Public Property mensajeria As Nullable(Of Boolean)
    Public Property firmas As Nullable(Of Boolean)
    Public Property pwdfirma As String
    Public Property archfirma As String
    Public Property especial As String
    Public Property id_ciudad As Nullable(Of Long)
    Public Property cargo As String

    Public Overridable Property Admin_Ciudades As Admin_Ciudades
    Public Overridable Property AdminActividad As AdminActividad
    Public Overridable Property AdminContacto As ICollection(Of AdminContacto) = New HashSet(Of AdminContacto)
    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property AdminTipoTercero As AdminTipoTercero
    Public Overridable Property Areas As Areas
    Public Overridable Property Clientes As Clientes
    Public Overridable Property Comentarios_Correspondencia As ICollection(Of Comentarios_Correspondencia) = New HashSet(Of Comentarios_Correspondencia)
    Public Overridable Property Correspondencia As ICollection(Of Correspondencia) = New HashSet(Of Correspondencia)
    Public Overridable Property Correspondencia1 As ICollection(Of Correspondencia) = New HashSet(Of Correspondencia)
    Public Overridable Property Documentos_Terceros As ICollection(Of Documentos_Terceros) = New HashSet(Of Documentos_Terceros)
    Public Overridable Property Solicitudes As ICollection(Of Solicitudes) = New HashSet(Of Solicitudes)
    Public Overridable Property Solicitudes1 As ICollection(Of Solicitudes) = New HashSet(Of Solicitudes)
    Public Overridable Property SucursalTerceros As ICollection(Of SucursalTerceros) = New HashSet(Of SucursalTerceros)
    Public Overridable Property Terceros_Correspondencia As ICollection(Of Terceros_Correspondencia) = New HashSet(Of Terceros_Correspondencia)
    Public Overridable Property Terceros1 As ICollection(Of Terceros) = New HashSet(Of Terceros)
    Public Overridable Property Terceros2 As Terceros
    Public Overridable Property Usuarios_Terceros As ICollection(Of Usuarios_Terceros) = New HashSet(Of Usuarios_Terceros)

End Class
