'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoDoc_TablaRetencion
    Public Property codigo As String
    Public Property gestion As Integer
    Public Property central As Integer
    Public Property CT As Boolean
    Public Property E As Boolean
    Public Property M As Boolean
    Public Property S As Boolean
    Public Property procedimientos As String
    Public Property id_tablaret As Long
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property TipoDocumento As String
    Public Property historico As Nullable(Of Integer)
    Public Property Original As Nullable(Of Boolean)
    Public Property D As Nullable(Of Boolean)
    Public Property id_tipo As Nullable(Of Long)
    Public Property tgestion As String
    Public Property tcentral As String
    Public Property thistorico As String

    Public Overridable Property AdminTablasReferencia As AdminTablasReferencia
    Public Overridable Property AdminTipoDocumento As AdminTipoDocumento

End Class
