'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transferencias
    Public Property id As Long
    Public Property fecha As Date
    Public Property id_documento As Long
    Public Property id_origen As Long
    Public Property id_destino As Long
    Public Property usuario As String

    Public Overridable Property Documentos As Documentos
    Public Overridable Property Ubicaciones As Ubicaciones
    Public Overridable Property Ubicaciones1 As Ubicaciones

End Class
