'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ubicaciones
    Public Property ubicacion As String
    Public Property descripcion As String
    Public Property id_tipo As Long
    Public Property id_sucursal As Long
    Public Property id_ubicacion As Nullable(Of Long)
    Public Property id As Long
    Public Property Capacidad As Nullable(Of Integer)
    Public Property Archivo As String

    Public Overridable Property AdminSucursal As AdminSucursal
    Public Overridable Property AdminTipoUbicacion As AdminTipoUbicacion
    Public Overridable Property Documentos As ICollection(Of Documentos) = New HashSet(Of Documentos)
    Public Overridable Property Solicitudes As ICollection(Of Solicitudes) = New HashSet(Of Solicitudes)
    Public Overridable Property Transferencias As ICollection(Of Transferencias) = New HashSet(Of Transferencias)
    Public Overridable Property Transferencias1 As ICollection(Of Transferencias) = New HashSet(Of Transferencias)
    Public Overridable Property Ubicaciones1 As ICollection(Of Ubicaciones) = New HashSet(Of Ubicaciones)
    Public Overridable Property Ubicaciones2 As Ubicaciones

End Class
