'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UsuariosWF
    Public Property empresa_id As Nullable(Of Long)
    Public Property usuario As String
    Public Property password As String
    Public Property nombre As String
    Public Property ID As Integer
    Public Property Cargo As String
    Public Property rol_id As Long
    Public Property perfil_id As Short
    Public Property email As String
    Public Property bloqueado As Boolean
    Public Property fecha_password As Nullable(Of Date)

    Public Overridable Property UsuariosSegmento As ICollection(Of UsuariosSegmento) = New HashSet(Of UsuariosSegmento)

End Class
