'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario_Sucursal
    Public Property id As Long
    Public Property id_usuario As Long
    Public Property id_sucursal As Long

    Public Overridable Property AdminSucursal As AdminSucursal

End Class
