'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario_Cliente
    Public Property id_usuario As Long
    Public Property id_cliente As Long
    Public Property id As Long
    Public Property todas As Nullable(Of Boolean)

    Public Overridable Property Clientes As Clientes

End Class
