'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property usuario As String
    Public Property password As String
    Public Property nombre As String
    Public Property email As String
    Public Property bloqueado As Boolean
    Public Property fecha_password As Nullable(Of Date)
    Public Property id_perfil As Long
    Public Property ID As Long
    Public Property Todos As Nullable(Of Boolean)
    Public Property Areas As Nullable(Of Boolean)
    Public Property Terceros As Nullable(Of Boolean)
    Public Property id_tercero As Nullable(Of Long)
    Public Property correspondencia As Nullable(Of Boolean)

    Public Overridable Property AdminPerfiles As AdminPerfiles

End Class
