'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UsuariosSegmento
    Public Property segmento_id As Integer
    Public Property usuario As String
    Public Property MSysId As Long

    Public Overridable Property Segmentos As Segmentos
    Public Overridable Property Usuarios As UsuariosWF

End Class
