'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ValidadorDocumentos
    Public Property id_tipo_documento As Long
    Public Property id_estado As Long
    Public Property cuantos As Integer
    Public Property id As Long

    Public Overridable Property AdminTipoDocumento As AdminTipoDocumento

End Class
