'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditarCorrespondencia
    
    '''<summary>
    '''lbNumeroRadicado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNumeroRadicado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNumeroRadicado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroRadicado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbFechaDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFechaDocumento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFechaDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaDocumento As Global.Infragistics.Web.UI.EditorControls.WebDatePicker
    
    '''<summary>
    '''WMFechaDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WMFechaDocumento As Global.Infragistics.Web.UI.EditorControls.WebMonthCalendar
    
    '''<summary>
    '''RQ_FechaDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_FechaDocumento As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDepartamento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartamento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCiudad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCiudad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbTipoIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTipoIngreso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTipoIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoIngreso As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbTipoCorrespondencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTipoCorrespondencia As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTipoCorrespondencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoCorrespondencia As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbTipoDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTipoDocumento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTipoDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoDocumento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRemitente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemitente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RQ_Remitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_Remitente As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbDependenciaRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDependenciaRemitente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDependenciaRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDependenciaRemitente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RQ_DependenciaRemitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_DependenciaRemitente As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbAsunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAsunto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAsunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsunto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RQ_Asunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_Asunto As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbSticker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSticker As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSticker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSticker As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RQ_Sticker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_Sticker As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbGuia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbGuia As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGuia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGuia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RQ_Guia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_Guia As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbObservaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservaciones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RQ_Observaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RQ_Observaciones As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbDOcumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDOcumentos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDocSeleccionado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocSeleccionado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RD1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''RD2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RD2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bttBuscarDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttBuscarDocumento As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RD3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RD3 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bttAgregarDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttAgregarDocumento As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RD4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RD4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bttEliminarDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEliminarDocumento As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lstDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDocumentos As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lbDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDocumentoTercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocumentoTercero As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''R4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lbTercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTercero As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTercero As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''R5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R5 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bttBuscarTercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttBuscarTercero As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''R6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R6 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bttAgregarTercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttAgregarTercero As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''R7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R7 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''bttEliminarTercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEliminarTercero As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lstTercerosDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstTercerosDocumento As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cvPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvPagina As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''SqlDpto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDpto As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SRC_TipoCorrespondencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SRC_TipoCorrespondencia As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCiudad As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlTipoDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlTipoDoc As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Hdd_id_documento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hdd_id_documento As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Hdd_id_tercero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hdd_id_tercero As Global.System.Web.UI.WebControls.HiddenField
End Class
