'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contactos
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''MGR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MGR As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''AJAX_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AJAX_Panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ExpGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpGrid As Global.Infragistics.Web.UI.GridControls.WebExcelExporter
    
    '''<summary>
    '''Exppdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exppdf As Global.Infragistics.Web.UI.GridControls.WebDocumentExporter
    
    '''<summary>
    '''bttNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttNuevo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEditar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEliminar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttExcel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttPdf As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''GridContactos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridContactos As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''Src_Contactos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Src_Contactos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''HCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HCliente As Global.System.Web.UI.WebControls.HiddenField
End Class
