'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FlujoProceso

    '''<summary>
    '''lblMsgFlujo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgFlujo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btGuardarFlujo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGuardarFlujo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsgGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgGen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btGenerarDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btGenerarDocs As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hddFlujoDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddFlujoDatos As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddTipoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddTipoId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddPlantilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddPlantilla As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddTipoIdGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddTipoIdGen As Global.System.Web.UI.WebControls.HiddenField

End Class
