'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Page_Terceros
    
    '''<summary>
    '''ExpGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpGrid As Global.Infragistics.Web.UI.GridControls.WebExcelExporter
    
    '''<summary>
    '''Exppdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exppdf As Global.Infragistics.Web.UI.GridControls.WebDocumentExporter
    
    '''<summary>
    '''bttNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttNuevo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEditar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEliminar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttContacto As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttExcel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttPdf As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''GridTerceros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridTerceros As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''Src_Terceros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Src_Terceros As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''HCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HCliente As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''BttNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BttNew As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BttEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BttEdit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BttDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BttDelete As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BttContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BttContact As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BttExc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BttExc1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Bttpd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bttpd1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''GridSucursales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridSucursales As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''Src_Sucursales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Src_Sucursales As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField
End Class
