'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Page_BackUp
    
    '''<summary>
    '''ExpGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpGrid As Global.Infragistics.Web.UI.GridControls.WebExcelExporter
    
    '''<summary>
    '''Exppdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exppdf As Global.Infragistics.Web.UI.GridControls.WebDocumentExporter
    
    '''<summary>
    '''bttNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttNuevo As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEditar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttEliminar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttExcel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''bttPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttPdf As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''GridClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridClientes As Global.Infragistics.Web.UI.GridControls.WebDataGrid
    
    '''<summary>
    '''Src_Clientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Src_Clientes As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Hdd_id_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hdd_id_usuario As Global.System.Web.UI.WebControls.HiddenField
End Class
